# Spam Classifier
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
Spam refers to unwanted email, often in the form of advertisements. In the literature, an email that is **not** spam is called *ham*. Most email providers offer automatic spam filtering, where spam emails will be moved to a separate inbox based on their contents. Of course this requires being able to scan an email and determine whether it is spam or ham, a classification problem. This is the subject of this assignment.

This assignment has two parts. Each part is worth 50% of the overall grade for this assignment.

For part one you will write a supervised learning based classifier to determine whether a given email is spam or ham. You must write and submit the code in this notebook. The training data is provided for you. You may use any classification method. Marks will be awarded primarily based on the accuracy of your classifier on unseen test data, but there are also marks for estimating how accurate you think your classifier will be.

In part two you will produce a short video explaining your implementation, any decisions or extensions you made, and what parameter values you used. This part is explained in more detail on the assignment page. The video file must be submitted with your assignment.

### Choice of Algorithm
While the classification method is a completely free choice, the assignment folder includes [a separate notebook file](data/naivebayes.ipynb) which can help you implement a Naïve Bayes solution. If you do use this notebook, you are still responsible for porting your code into *this* notebook for submission. A good implementation should give a high  enough accuracy to get a good grade on this section (50-70%).

You could also consider a k-nearest neighbour algorithm, but this may be less accurate. Logistic regression is another option that you may wish to consider.

If you are looking to go beyond the scope of the unit, you might be interested in building something more advanced, like an artificial neural network. This is possible just using `numpy`, but will require significant self-directed learning. *Extensions like this are left unguided and are not factored into the unit workload estimates.*

**Note:** you may use helper functions in libraries like `numpy` or `scipy`, but you **must not** import code which builds entire models for you. This includes but is not limited to use of libraries like `scikit-learn`, `tensorflow`, or `pytorch` – there will be plenty of opportunities for these libraries in later units. The point of this assignment is to understand code the actual algorithm yourself. ***If you are in any doubt about any particular library or function please ask a tutor.*** Submissions which ignore this will receive penalties or even zero marks.

If you choose to implement more than one algorithm, please feel free to include your code and talk about it in part two (your video presentation), but only the code in this notebook will be used in the automated testing.

## Training Data
The training data is described below and has 1000 rows. There is also a 500 row set of test data. These are functionally identical to the training data, they are just in a separate csv file to encourage you to split out your training and test data. You should consider how to best make use of all available data without overfitting, and to help produce an unbiased estimate for your classifier's accuracy.

The cell below loads the training data into a variable called `training_spam`.

In [1]:
import numpy as np

training_spam = np.loadtxt(open("data/training_spam.csv"), delimiter=",").astype(np.int)
print("Shape of the spam training data set:", training_spam.shape)
print(training_spam)

Shape of the spam training data set: (1000, 55)
[[1 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [1 1 1 ... 1 1 0]
 [1 0 0 ... 1 1 1]]


<ipython-input-1-9b07313e2dc5>:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  training_spam = np.loadtxt(open("data/training_spam.csv"), delimiter=",").astype(np.int)


Your training set consists of 1000 rows and 55 columns. Each row corresponds to one email message. The first column is the _response_ variable and describes whether a message is spam `1` or ham `0`. The remaining 54 columns are _features_ that you will use to build a classifier. These features correspond to 54 different keywords (such as "money", "free", and "receive") and special characters (such as ":", "!", and "$"). A feature has the value `1` if the keyword appears in the message and `0` otherwise.

As mentioned there is also a 500 row set of *test data*. It contains the same 55 columns.

In [2]:
testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(np.int)
print("Shape of the spam testing data set:", testing_spam.shape)
print(testing_spam)

Shape of the spam testing data set: (500, 55)
[[1 0 0 ... 1 1 1]
 [1 1 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]]


<ipython-input-2-7b09f440222b>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(np.int)


## Part One
Write all of the code for your classifier below this cell. There is some very rough skeleton code in the cell directly below. You may insert more cells below this if you wish, but you must not duplicate any cells as this can break the grading script.

### Submission Requirements
Your code must provide a variable with the name `classifier`. This object must have a method called `predict` which takes input data and returns class predictions. The input will be a single $n \times 54$ numpy array, your classifier should return a numpy array of length $n$ with classifications. There is a demo in the cell below, and a test you can run before submitting to check your code is working correctly.

Your code must run on our test machine in under 30 seconds. If you wish to train a more complicated model (e.g. neural network) which will take longer, you are welcome to save the model's weights as a file and then load these in the cell below so we can test it. You must include the code which computes the original weights, but this must not run when we run the notebook – comment out the code which actually executes the routine and make sure it is clear what we need to change to get it to run. Remember that we will be testing your final classifier on additional hidden data.

In [3]:
# This skeleton code simply classifies every input as ham
#
# Here you can see there is a parameter k that is unused, the
# point is to show you how you could set up your own. You might
# also pass in extra data via a train method (also does nothing
# here). Modify this code as much as you like so long as the 
# accuracy test in the cell below runs.

class SpamClassifier:
    def __init__(self, alpha=1.0):
        self.alpha = alpha
        self.log_class_priors = 0
        self.theta = 0

    # TRAINING part A
    def estimate_log_class_priors(self, data):
        """
        Given a data set with binary response variable (0s and 1s) in the
        left-most column, calculate the logarithm of the empirical class priors,
        that is, the logarithm of the proportions of 0s and 1s:
            log(p(C=0)) and log(p(C=1))

        :param data: a two-dimensional numpy-array with shape = [n_samples, 1 + n_features]
                     the first column contains the binary response (coded as 0s and 1s).

        :return log_class_priors: a numpy array of length two
        """
        ### YOUR CODE HERE...
        data_labels = data[:, 0]
        n_samples = len(data_labels)
        data_features = data[:, 1:]
        n_features = len(data_features[0, :])
        # counting the number of samples that are associated to class C = 0 (ham) and C = 0 (spam)
        data_cnt_c1 = np.count_nonzero(data_labels == 1)
        data_cnt_c0 = n_samples - data_cnt_c1

        # proportions (probability) of sample that are associated to class C = 0 (ham) and C = 0 (spam)
        p_value_0 = data_cnt_c0 / n_samples
        p_value_1 = data_cnt_c1 / n_samples

        # logarithm of the probability log(p(C=0)) and log(p(C=1))
        # log_class_priors size is 1 row and 2 cols (log_class_priors.shape= (2,))
        log_class_priors = np.array([np.log(p_value_0), np.log(p_value_1)])

        self.log_class_priors =  log_class_priors

    # TRAINING part B    
    def estimate_log_class_conditional_likelihoods(self, data):
        """
        Given a data set with binary response variable (0s and 1s) in the
        left-most column and binary features (words), calculate the empirical
        class-conditional likelihoods, that is,
        log(P(w_i | c)) for all features w_i and both classes (c in {0, 1}).

        Assume a multinomial feature distribution and use Laplace smoothing
        if alpha > 0.

        :param data: a two-dimensional numpy-array with shape = [n_samples, 1 + n_features]

        :return theta:
            a numpy array of shape = [2, n_features]. theta[j, i] corresponds to the
            logarithm of the probability of feature i appearing in a sample belonging 
            to class j.
        """
        ### YOUR CODE HERE...
        alpha = self.alpha
        # splitting the data into the column label and the columns features
        data_labels = data[:, 0]
        data_features = data[:, 1:]
        # split the "data" in two parts, the one that are associated to c=0 (ham) and c=1 (spam)
        feature_c0 = data_features[data_labels == 0]
        feature_c1 = data_features[data_labels == 1]

        n_samples = len(data_labels)
        n_features = len(data_features[0, :])
        # counting the number of sample that are associated to class c=0 and c=1
        data_cnt_c1 = np.count_nonzero(data_labels == 1)
        data_cnt_c0 = n_samples - data_cnt_c1

        # where n_c0_w is the vector of length n_features that contains
        # n0,w_1  n0,w_2 n0,w_3 ... n0,w_n_features
        # where n0,w_1 is the number of time the word w_1=1  for c=0
        # where n_c1_w is the vector of length n_features that contains
        # n1,w_1  n1,w_2 n0,w_3 ... n1,w_n_features
        # where n1,w_1 is the number of time the word w_1=1  for c=1
        n_c0_w = np.empty(shape=(1, n_features), dtype=float)
        n_c1_w = np.empty(shape=(1, n_features), dtype=float)
        for idx in range(n_features):
            n_c0_w[0, idx] = np.count_nonzero(feature_c0[:, idx] == 1)
            n_c1_w[0, idx] = np.count_nonzero(feature_c1[:, idx] == 1)

        # n0 is the sum of the elements of the vector n_c0_w
        # n1 is the sum of the elements of the vector n_c1_w
        n_c0 = np.sum(n_c0_w)
        n_c1 = np.sum(n_c1_w)

        # calculation of the logarithm of the empirical class-conditional likelihoods
        # for all words 𝑤𝑖 and both classes (𝑐∈0,1) -> log(P(w_i | c)
        theta_0 = np.empty(shape=(1, n_features), dtype=float)
        theta_1 = np.empty(shape=(1, n_features), dtype=float)
        for idx in range(n_features):
            theta_0[0, idx] = np.log( (n_c0_w[0, idx] + alpha) / (n_c0 + n_features * alpha) )
            theta_1[0, idx] = np.log( (n_c1_w[0, idx] + alpha) / (n_c1 + n_features * alpha) )


        # concatenate the row theta_0 and the row theta_1 to form theta 2xn_features
        theta = np.concatenate((theta_0, theta_1), axis = 0)

        self.theta = theta
    # TRAINING part A and B
    def train(self, data):
        self.estimate_log_class_priors(data)
        self.estimate_log_class_conditional_likelihoods(data)

    # PREDICTION
    def predict(self, new_data):
        """
        Given a new data set with binary features, predict the corresponding
        response for each instance (row) of the new_data set.

        :param new_data: a two-dimensional numpy-array with shape = [n_test_samples, n_features].
        :param log_class_priors: a numpy array of length 2.
        :param log_class_conditional_likelihoods: a numpy array of shape = [2, n_features].
            theta[j, i] corresponds to the logarithm of the probability of feature i appearing
            in a sample belonging to class j.
        :return class_predictions: a numpy array containing the class predictions for each row
            of new_data.
        """
        ### YOUR CODE HERE...
        n_features = len(new_data[0, :])
        n_samples = len(new_data[:, 0])

        theta = self.theta  # array size 2 x n_features
        log_class_priors = self.log_class_priors
        # the summation of w_i * theta can be written in matrices terms
        new_data_trasp = np.transpose(new_data)  # new_data_trasp array size n_features x n_samples

        # calculation of the summation (wi *log(theta))
        # theta(2 x n_features) * new_data_trasp(n_features x 1) = (2 x 1)
        # w_theta for all samples is size 2 x n_samples
        w_theta = np.empty(shape=(2, n_samples), dtype=float)
        for c in range(theta.shape[0]):
            for sample in range(n_samples):  # sample looping through the new_data columns (1000 samples) selecting an entire column
                # w_theta(2 x 1)
                w_theta[c, sample] = np.dot(theta[c, :], new_data_trasp[:, sample])  # new_data_trasp[:,sample] array size n_features x 1
        # log_class_priors size is (1x2), so let's reshape it in (2x1)
        log_class_priors_col = log_class_priors.reshape((-1, 1))

        # sum log_class_priors_col (2x1) with each single column of the w_theta (2x1) and then loop through all n_samples of w_theta (2 x n_samples)
        res = np.empty(shape=(2, n_samples), dtype=float)
        for sample in range(n_samples):
            res[:, sample] = log_class_priors_col[:,0] + w_theta[:, sample]

        # find the "𝑐∈{0,1}" that has the highest probability value per sample (class_predictions size 1x1000)
        # gives back the position of the maximum value along the columns (position 0 means c=0 and position 1 means c=1)
        class_predictions = np.argmax(res,axis=0)  

        return class_predictions

    
def create_classifier():
    classifier = SpamClassifier(alpha=1.0)
    classifier.train(training_spam)
    return classifier

classifier = create_classifier()

### Accuracy Estimate
In the cell below there is a function called `my_accuracy_estimate()` which returns `0.5`. Before you submit the assignment, write your best guess for the accuracy of your classifier into this function, as a percentage between `0` and `1`. So if you think you will get 80% of inputs correct, return the value `0.8`. This will form a small part of the marking criteria for the assignment, to encourage you to test your own code.

In [4]:
def my_accuracy_estimate():
    return 0.87

Write all of the code for your classifier above this cell.

### Testing Details
Your classifier will be tested against some hidden data from the same source as the original. The accuracy (percentage of classifications correct) will be calculated, then benchmarked against common methods. At the very high end of the grading scale, your accuracy will also be compared to the best submissions from other students (in your own cohort and others!). Your estimate from the cell above will also factor in, and you will be rewarded for being close to your actual accuracy (overestimates and underestimates will be treated the same).

#### Test Cell
The following code will run your classifier against the provided test data. To enable it, set the constant `SKIP_TESTS` to `False`.

The original skeleton code above classifies every row as ham, but once you have written your own classifier you can run this cell again to test it. So long as your code sets up a variable called `classifier` with a method called `predict`, the test code will be able to run. 

Of course you may wish to test your classifier in additional ways, but you *must* ensure this version still runs before submitting.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [6]:
SKIP_TESTS = True

if not SKIP_TESTS:
    testing_spam = np.loadtxt(open("data/testing_spam.csv"), delimiter=",").astype(np.int)
    test_data = testing_spam[:, 1:]
    test_labels = testing_spam[:, 0]

    predictions = classifier.predict(test_data)
    accuracy = np.count_nonzero(predictions == test_labels)/test_labels.shape[0]
    print(f"Accuracy on test data is: {accuracy}")

In [7]:
import sys
import pathlib

fail = False;

if not SKIP_TESTS:
    fail = True;
    print("You must set the SKIP_TESTS constant to True in the cell above.")
    
p3 = pathlib.Path('./spamclassifier.ipynb')
if not p3.is_file():
    fail = True
    print("This notebook file must be named spamclassifier.ipynb")
    
if "create_classifier" not in dir():
    fail = True;
    print("You must include a function called create_classifier.")

if "my_accuracy_estimate" not in dir():
    fail = True;
    print("You must include a function called my_accuracy_estimate.")
else:
    if my_accuracy_estimate() == 0.5:
        print("Warning:")
        print("You do not seem to have provided an accuracy estimate, it is set to 0.5.")
        print("This is the actually the worst possible accuracy – if your classifier")
        print("got 0.1 then it could invert its results to get 0.9!")
    
print("INFO: Make sure you follow the instructions on the assignment page to submit your video.")
print("Failing to include this could result in an overall grade of zero for both parts.")
print()

if fail:
    sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
else:
    print("All checks passed. When you are ready to submit, upload the notebook and readme file to the")
    print("assignment page, without changing any filenames.")
    print()
    print("If you need to submit multiple files, you can archive them in a .zip file. (No other format.)")

INFO: Make sure you follow the instructions on the assignment page to submit your video.
Failing to include this could result in an overall grade of zero for both parts.

All checks passed. When you are ready to submit, upload the notebook and readme file to the
assignment page, without changing any filenames.

If you need to submit multiple files, you can archive them in a .zip file. (No other format.)


In [ ]:
# This is a test cell. Please do not modify or delete.